In [1]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [2]:
x = np.random.rand(3, 3, 3)
print(x)

np.matmul(x, np.linalg.inv(x))
x @ np.linalg.inv(x)

[[[0.06350375 0.06937585 0.66206769]
  [0.43149987 0.56904671 0.48370316]
  [0.04273823 0.49656376 0.04025444]]

 [[0.44007468 0.87712096 0.83660416]
  [0.61634181 0.32303642 0.07533095]
  [0.56464537 0.13379307 0.94229124]]

 [[0.06582023 0.93360946 0.67589532]
  [0.69719187 0.93547094 0.94510344]
  [0.72631106 0.56341525 0.41888865]]]


array([[[ 1.00000000e+00, -2.66332875e-17,  2.43702810e-17],
        [ 4.77964133e-17,  1.00000000e+00,  7.18268844e-17],
        [ 2.76154793e-18, -1.19176826e-18,  1.00000000e+00]],

       [[ 1.00000000e+00, -8.04024734e-17, -4.94455840e-17],
        [-1.06735376e-17,  1.00000000e+00, -2.29234412e-17],
        [ 4.86936461e-17, -2.81319943e-16,  1.00000000e+00]],

       [[ 1.00000000e+00, -6.16406370e-16,  9.63788461e-17],
        [-1.83789955e-16,  1.00000000e+00, -2.64611812e-16],
        [ 1.12268559e-16, -2.93122483e-17,  1.00000000e+00]]])

#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [3]:
A = np.array([[1, 1], [2, 4]])
B = np.array([25, 64])

x = np.linalg.solve(A, B)
print(x)

np.allclose(A@x, B)

[18.  7.]


True