In [1]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.95516855 0.98391351 0.11711944 0.54605616 0.2175664 ]
 [0.74705919 0.66915946 0.99689319 0.93750868 0.48609701]
 [0.16251386 0.12432103 0.50502613 0.3345306  0.65283034]]


 #### 연산 함수
 - add, substract, multiply, divide

In [3]:
np.add(x, y)

array([[ 0.95516855,  1.98391351,  2.11711944,  3.54605616,  4.2175664 ],
       [ 5.74705919,  6.66915946,  7.99689319,  8.93750868,  9.48609701],
       [10.16251386, 11.12432103, 12.50502613, 13.3345306 , 14.65283034]])

In [4]:
np.divide(x, y)

array([[ 0.        ,  1.0163495 , 17.07658415,  5.49394039, 18.38519209],
       [ 6.69291011,  8.9664727 ,  7.02181547,  8.53325437, 18.5148228 ],
       [61.53321156, 88.48060897, 23.76114655, 38.86042081, 21.44508158]])

In [6]:
x + y

array([[ 0.95516855,  1.98391351,  2.11711944,  3.54605616,  4.2175664 ],
       [ 5.74705919,  6.66915946,  7.99689319,  8.93750868,  9.48609701],
       [10.16251386, 11.12432103, 12.50502613, 13.3345306 , 14.65283034]])

In [5]:
x / y

array([[ 0.        ,  1.0163495 , 17.07658415,  5.49394039, 18.38519209],
       [ 6.69291011,  8.9664727 ,  7.02181547,  8.53325437, 18.5148228 ],
       [61.53321156, 88.48060897, 23.76114655, 38.86042081, 21.44508158]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [7]:
print(y)

[[0.95516855 0.98391351 0.11711944 0.54605616 0.2175664 ]
 [0.74705919 0.66915946 0.99689319 0.93750868 0.48609701]
 [0.16251386 0.12432103 0.50502613 0.3345306  0.65283034]]


In [8]:
np.mean(y)

0.5623842364436052

In [9]:
y.mean()

0.5623842364436052

In [10]:
np.max(y)

0.9968931862069721

In [13]:
np.argmax(y) # 제일 큰 값의 인덱스

7

In [12]:
np.var(y), np.median(y), np.std(y)

(0.0963612299407635, 0.5460561611368505, 0.3104210526700203)

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [14]:
y

array([[0.95516855, 0.98391351, 0.11711944, 0.54605616, 0.2175664 ],
       [0.74705919, 0.66915946, 0.99689319, 0.93750868, 0.48609701],
       [0.16251386, 0.12432103, 0.50502613, 0.3345306 , 0.65283034]])

In [15]:
np.sum(y)

8.435763546654078

In [16]:
np.cumsum(y)

array([0.95516855, 1.93908206, 2.0562015 , 2.60225766, 2.81982406,
       3.56688325, 4.2360427 , 5.23293589, 6.17044456, 6.65654157,
       6.81905544, 6.94337646, 7.4484026 , 7.7829332 , 8.43576355])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [17]:
z = np.random.randn(10)
print(z)

[-0.75585721 -0.9358724   0.57777647  1.25387053  1.56767902  0.31833999
 -1.48960818 -2.48866585  0.51227043 -1.90877042]


In [18]:
z > 0

array([False, False,  True,  True,  True,  True, False, False,  True,
       False])

In [19]:
np.any(z > 0)

True

In [20]:
np.all(z != 0)

True

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [21]:
z = np.random.randn(10)
print(z)

[ 0.15804499  1.04397312  0.57988887 -0.88959286 -1.11438566  0.15528141
  0.05554058  0.81244382  0.53890128  0.18123107]


In [22]:
np.where(z > 0, z, 0)

array([0.15804499, 1.04397312, 0.57988887, 0.        , 0.        ,
       0.15528141, 0.05554058, 0.81244382, 0.53890128, 0.18123107])