In [1]:
import numpy as np

In [2]:
x = np.arange(36).reshape(3, 4, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [3]:
x[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
x[1]

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [5]:
x[1, 2]

array([18, 19, 20])

In [6]:
x[1, 2, 1]

19

## 슬라이싱
- 1차원 벡터 슬라이싱

In [7]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

## 2차원 행렬 슬라이싱

In [9]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
x[:, 1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [11]:
x[:, :2]

array([[0, 1],
       [5, 6]])

In [13]:
x[0, :2]

array([0, 1])

In [14]:
x[:1, :2]

array([[0, 1]])

## 인덱싱을 하면 차원이 하나 줄어든다
## 슬라이싱은 차원을 유지하며 자른다

## 3차원 텐서 슬라이싱

In [16]:
x = np.arange(54).reshape(2, 9, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]]


In [26]:
x[:1, :2, :]
# 3차원 텐서

array([[[0, 1, 2],
        [3, 4, 5]]])

In [27]:
x[0, :2, :]
# 2차원 행렬

array([[0, 1, 2],
       [3, 4, 5]])